name: Diff SM8250 Kernel vs AOSP Common Kernel

on:
  workflow_dispatch:

jobs:
  diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our SM8250 kernel
        uses: actions/checkout@v4
        with:
          repository: "Yew12347/android_kernel_xiaomi_sm8250"
          path: sm8250
          fetch-depth: 0

      - name: Clone AOSP common kernel tag
        run: |
          git clone --depth=1 \
            --branch android16-6.12-2025-12_r22 \
            --single-branch \
            https://android.googlesource.com/kernel/common \
            aosp-common

      - name: Generate full diff patch
        run: |
          git diff --no-index aosp-common sm8250 > full_aosp_vs_sm8250.patch || true

      - name: Upload diff patch
        uses: actions/upload-artifact@v4
        with:
          name: sm8250-vs-aosp-patch
          path: full_aosp_vs_sm8250.patch
